---
title: "eds221_day3_interactive"
format: html
editor: visual
---

## Conditional Statements

```{r}
temperature <- 95

if (temperature > 97) {
  print("Temperature warning")
}else 
  print("No temperature warning")
```

Create an if else statement for blue whale lengths. Create a variable blue whale which has a value of 40

```{r}
blue_whale <- 15
if (blue_whale > 35) { 
  print("GIANT")
  } else if (blue_whale <= 20) {
    print("SMALL")
  } else (
      print("MEDIUM"))
```

## Switch Statement

```{r}
housing_type <- "single"

switch(housing_type,
       "single" = print("400"),
       "double" = print("750"),
       "whole" = print("1100"))

#This looks for which one of these statements matches the value of the input value and do whatever is on the right, which in this case is print a value. 

if(housing_type == "whole") {
  print("400")
} else if (housing_type == "double"){
  print("750")
} else if (housing_type == "single"){
    print("400")
    }
```

### For Loops

```{r}
height <- c(58, 61, 65, 72, 89, 94)

#We are creating a for loop that is saying for the length of the sequence height, iterate through the height values and do the calculation dividing by 2. Then print those values
for (i in seq_along(height)) {
  half_height = height[i] / 2 
  print(half_height)
}

#For each value in the height vector, return the sum of the value + the one right after it....
for (i in seq_along(height)) {
  sum_height = height[i] + height[i + 1]
  print(sum_height)
}

#If we want to not have an "NA" for the last value we can modify:
for (i in seq(1:(length(height) - 1))) {
  sum_height = height[i] + height[i + 1]
  print(sum_height)
}

#Write a for loop that calculates the value of height for each element divided by the mean of the entire height vector 

mean_height <- mean(height)
for (i in seq_along(height)) {
  mean_heights = height[i] / mean_height
  print(mean_heights)
}

```
